# This is a basic workflow to help you get started with Actions

name: Node Integration Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: packer test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Authentication with GCP
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{secrets.GCP_PROFILE}}"

      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v3.0.0
        id: setup
        with:
            version: "latest"

      - name: Run `packer init`
        id: init
        run: 
            |
            cd packer/
            "packer init ."

      - name: files check
        run: ls -al

      - name: Run `packer fmt`
        id: fmt
        env: 
            PACKER_CONFIG: ${{secrets.PACKER_CONFIG}}
        run: |
            echo "$PACKER_CONFIG" > ./packer/values.pkrvars.hcl
            packer fmt -var-file="values.pkrvars.hcl" .

      - name: files check
        run: ls -al
    
      - name: Run `packer validate`
        id: validate
        run: packer validate -var-file="values.pkrvars.hcl" .
        
        
  
          
